### ISSUE TITLE
compilation error due to mising sources?

### ISSUE THREAD

**Issue by pyromaniac78** [adagate-io/adagate-api#2]
Hi,
I tried to compile adagate-api, but get these errors:
`[ERROR] /cardano/adagate-api/src/main/java/io/adagate/ApiConstants.java:[3,25] package io.adagate.models does not exist
[ERROR] /cardano/adagate-api/src/main/java/io/adagate/handlers/routes/AbstractRouteHandler.java:[5,25] package io.adagate.models does not exist
[ERROR] /cardano/adagate-api/src/main/java/io/adagate/handlers/routes/epochs/AbstractEpochHandler.java:[5,25] package io.adagate.models does not exist
[ERROR] /cardano/adagate-api/src/main/java/io/adagate/handlers/routes/addresses/AbstractAddressHandler.java:[5,25] package io.adagate.models does not exist
[ERROR] /cardano/adagate-api/src/main/java/io/adagate/handlers/routes/accounts/AbstractAccountHandler.java:[5,25] package io.adagate.models does not exist
[ERROR] /cardano/adagate-api/src/main/java/io/adagate/handlers/database/assets/AbstractAssetHandler.java:[4,25] package io.adagate.models does not exist
[ERROR] /cardano/adagate-api/src/main/java/io/adagate/handlers/routes/assets/AbstractGetAssets.java:[6,25] package io.adagate.models does not exist
[ERROR] /cardano/adagate-api/src/main/java/io/adagate/handlers/routes/assets/GetAssets.java:[5,25] package io.adagate.models does not exist
[ERROR] /cardano/adagate-api/src/main/java/io/adagate/handlers/routes/blocks/GetBlockTransactions.java:[5,25] package io.adagate.models does not exist
[ERROR] /cardano/adagate-api/src/main/java/io/adagate/verticles/database/DatabaseSubscriberVerticle.java:[3,39] package io.adagate.database.subscribers does not exist
[ERROR] /cardano/adagate-api/src/main/java/io/adagate/verticles/database/DatabaseSubscriberVerticle.java:[4,39] package io.adagate.database.subscribers does not exist
[ERROR] /cardano/adagate-api/src/main/java/io/adagate/verticles/database/DatabaseSubscriberVerticle.java:[5,39] package io.adagate.database.subscribers does not exist
[ERROR] /cardano/adagate-api/src/main/java/io/adagate/verticles/database/DatabaseSubscriberVerticle.java:[8,29] cannot find symbol
  symbol:   class CardanoApiModuleException
  location: package io.adagate.exceptions
`
are there some sources missing in the repository?

**Comment by will-break-it** [comment]
Added the missing types! Also made sure a fresh clone does not have compile issues!
